import os
from pathlib import Path

input_dir = Path("genshin/noise_train___/")
executable_path = Path("AudioProcess_20250802/AudioPreProcess.exe")

for root, dirs, files in os.walk(input_dir):
    for file in files:
        if file.endswith(".wav"):
            input_file = str(Path(root) / file)
            if "_train" in input_file:
                output_file = str(input_file).replace("_train", "_train_processed")
            if "_test" in input_file:
                output_file = str(input_file).replace("_test", "_test_processed")
            os.makedirs(os.path.dirname(output_file), exist_ok=True)
            os.system(f"{executable_path} {input_file} {output_file} 4")

# Clean up log files generated by the executable
for log_file in Path(executable_path.parent).glob("*.log"):
    if log_file.is_file():
        os.remove(log_file)